language: python
python:
    - 2.7
install: 
    - pip install -r requirements.txt
    - pip install coveralls --use-wheel

script: python setup.py develop && py.test -v --cov pyrefflat --cov-report term-missing 


after_success:
    - coveralls
